# windows ci

build: off

environment:

  matrix:
    - PYTHON: 'C:\Python27'
      PYTHON_VERSION: '2.7.13'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\Python27-x64'
      PYTHON_VERSION: '2.7.13'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\Python36'
      PYTHON_VERSION: '3.6.1'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\Python36-x64'
      PYTHON_VERSION: '3.6.1'
      PYTHON_ARCH: '64'

install:
  - 'python --version
  - 'python -c "import struct; print(struct.calcsize('P') * 8)"'
  - 'pip install --disable-pip-version-check --user --upgrade pip'

build: off

test_script:
  - '%CMD_IN_ENV% python setup.py test'

test: off

deploy: off
