
language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: pyver=python
    - os: linux
      python: '3.6'
      env: pyver=python
    - os: osx
      language: generic
      env: pyver=python
    - os: osx
      language: generic
      env: pyver=python3   

# sudo: required

install:
  - if [[ ("$TRAVIS_OS_NAME" == "osx") && ("$pyver" == "python3") ]]; then brew upgrade python; fi

script:
  - $pyver -c "import sys,struct; print('\npython v{0}.{1}.{2} says it\'s a {3}bit machine'.format(sys.version_info.major, sys.version_info.minor, sys.version_info.micro, struct.calcsize('P') * 8))"
  - $pyver setup.py test
