
language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: pyver=python
    - os: linux
      python: '3.6'
      env: pyver=python
    - os: osx
      language: generic
      env: pyver=python
    - os: osx
      language: generic
      env: pyver=python3   

before-install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $pyver; fi

script:
  - $pyver -c "import struct; print('python says it\'s a {0}bit machine'.format(struct.calcsize('P') * 8))"
  - $pyver setup.py install
  - $pyver setup.py test
